# Generated by Django 4.2.2 on 2023-06-15 08:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='President',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(101)])),
                ('genre', models.CharField(choices=[('homme', 'Homme'), ('femme', 'Femme'), ('autre', 'Other')], max_length=5)),
                ('image', models.ImageField(upload_to='image_president')),
            ],
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('population', models.BigIntegerField()),
                ('continent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pays', to='app.continent')),
                ('president', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pays', to='app.president')),
            ],
        ),
    ]
